/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/decorations/tree-2.gltf -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { MODEL } from '@/app/_constants/models';

type GLTFResult = GLTF & {
  nodes: {
    ['tree-lime']: THREE.Mesh;
  };
  materials: {
    color_main: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>;

export function LimeTree(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MODEL.decoration.tree2.modelUrl) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tree-lime'].geometry} material={materials.color_main} castShadow />
    </group>
  );
}

useGLTF.preload(MODEL.decoration.tree2.modelUrl);
