/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/decorations/table.gltf -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { MODEL } from '@/app/_constants/models';

type GLTFResult = GLTF & {
  nodes: {
    tableLarge: THREE.Mesh;
  };
  materials: {
    ['BrownDark.074']: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>;

export function Table(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MODEL.decoration.table.modelUrl) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tableLarge.geometry}
        material={materials['BrownDark.074']}
        rotation={[Math.PI / 2, 0, 0]}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(MODEL.decoration.table.modelUrl);
